# Inventario inicial en formato INI para Cómo 03
# Sustituye <IP_DEL_SERVIDOR> por la dirección IPv4 pública de tu nodo CentOS Stream 10

[webservers]
cherry-node ansible_host=<IP_DEL_SERVIDOR> ansible_user=root

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
